services:
  station:
    # image: mrgorre/devstation:latest
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - ${HOME}/.env
    volumes:
      - ./app:/app
      - ./sandbox:/sandbox
      - ./.config:/root/.config
      - ./ssh-config:/root/ssh-config
    #  ### For gui
    #   - /tmp/.X11-unix:/tmp/.X11-unix
    # environment:
    #   - DISPLAY
  # ### DB
  # pg_db:
  #   image: postgres:latest
  #   restart: unless-stopped
  #   environment:
  #     - POSTGRES_USER:pg_user
  #     - POSTGRES_PASSWORD:pg_pass
  #     - POSTGRES_DB:pg_db
  #     - PGDATA:/var/lib/postgresql/data/pgdata
  #   healthcheck:
  #     test: [ "CMD-SHELL", "pg_isready -U pg_user -d pg_db" ]
  #     interval: 30s
  #     timeout: 10s
  #     retries: 5
  #   volumes:
  #    - ./data/pg_data:/var/lib/postgresql/data
