services:
  station:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./app:/app
      - ./sandbox:/sandbox
      - ./.config:/root/.config
      - ./ssh-config:/root/ssh-config
      - ./.data/local:/root/.local 
      - ./.data/cache:/root/.cache 
