services:
  station:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
        - ${HOME}/.env
    volumes:
      - ./app:/app
      - ./sandbox:/sandbox
      - ./.config:/root/.config
      - ./ssh-config:/root/ssh-config
